package ses;
/**
 * 
 * @author Jatin Taneja 557
 * @author Bhupender Khedar 706
 * @author Rajinder Singh Pathania 238
 * @author Kaushal Singh 583
 */
public class PostGraduateStudent extends Student {
	/**
	 * A class which will inherit few fields from Student class to initialize with help of super
	 */
	
	// This static variable would be used for creating dynamic id for each instance created
	private static int autoGeneratedId = 100;  
	private String id;
	private String majorsIn;
	/**
	 * 
	 * @param firstName
	 * @param lastName
	 * @param age
	 * @param address
	 * @param majorsIn
	 */
	public PostGraduateStudent(String firstName,String lastName, int age, String address , String majorsIn) {
		super(firstName, lastName, age, address);
		autoGeneratedId += 1;
		this.majorsIn = majorsIn;
		this.id = "PG"+autoGeneratedId;
		
	}
	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * @return the majorsIn
	 */
	public String getMajorsIn() {
		return majorsIn;
	}
	/**
	 * @param majorsIn the majorsIn to set
	 */
	public void setMajorsIn(String majorsIn) {
		this.majorsIn = majorsIn;
	}
	@Override
	public String toString() {
		return "PostGraduateStudent [id=" + id + ", majorsIn=" + majorsIn + "]";
	}
	
	
}
