package ses;
/**
 * 
 * @author Jatin Taneja 557
 * @author Bhupender Khedar 706
 * @author Rajinder Singh Pathania 238
 * @author Kaushal Singh 583
 */
public class UnderGraduateStudent extends Student{
	/**
	 * A undergraduate class which will inherit few properties from Student and generate 
	 * dynamic id for each undergraduatestudent instance created
	 */
	private static int autoGeneratedId = 100;
	private String id;
	
	/**
	 * 
	 * @param firstName
	 * @param lastName
	 * @param age
	 * @param address
	 */
	public UnderGraduateStudent(String firstName,String lastName, int age, String address) {
		super(firstName, lastName, age, address);
		autoGeneratedId += 1;
		this.id = "UG"+autoGeneratedId;
		
	}
	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
	@Override
	public String toString() {
		return "UnderGraduateStudent [id=" + id + "]";
	}
}
